server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE-TEST #给提供者取一个名称
    datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:org/morality/mapper/*Mapper.xml
  type-aliases-package: org.morality.domain,org.morality.query
eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka #告诉服务提供者要把服务注册到哪儿
  instance:
    prefer-ip-address: true #显示客户端真实ip